server:
  port : 9081
spring:
  security:
    user:
      name: yoga
      password: password
      roles: manager

  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: admin


  jpa:
    hibernate:
      ddl-auto: update







